name: Bug Issue
description: Use template to submit a Bug
title: "[Bug]: "
assignees:
  - yefeizhou
body:
- type: dropdown
  id: component
  attributes:
    label: Which component impacted?
    multiple: true
    options:
      - Decode
      - Encode
      - Video Processing
      - Build
      - Not sure
- type: dropdown
  id: regression
  attributes:
    label: Is it regression? Good in old configuration?
    multiple: false
    options:
      - Yes, it's good in old version
      - No, this issue exist a long time
- type: textarea
  attributes:
    label: What happened?
    description: |
      Please provide reproduce steps and sample cmdline if possible which help us to debug it.
      If it's regression, please provide good/bad commit/configuration.
    placeholder: |
      1. In Linux or Windows or Browser or Applications...
      2. With libva/libva-utils/gmmlib/media-driver version...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: dropdown
  id: usage
  attributes:
    label: What's the usage scenario when you are seeing the problem?
    multiple: true
    options:
      - Transcode for media delivery
      - Playback
      - Web browser
      - Cloud Gaming
      - Video Analytics
      - Video Conference
      - Immersive Media
      - Content Creation
      - Game Streaming
      - Others
  validations:
    required: true
- type: textarea
  attributes:
    label: What impacted?
    description: Any program or milestone would be impacted if issue yet resolved? Please provide the information as detail as possible to help us understand and prioritize the issues.
    placeholder: If you select "Others" for above usage, please describe your usage scenario here to help us understand the impact.
  validations:
    required: false
- type: textarea
  attributes:
    label: Debug Information
    description: |
      Please provide debug information as detail as possible to accelerate issue resolved.
      1. What's libva/libva-utils/gmmlib/media-driver version?
      2. Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
      3. Could you provide vainfo log by `vainfo >vainfo.log 2>&1`?
      4. Could you provide libva trace log? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
      5. Could you attach dmesg log if GPU hang by `dmesg >dmesg.log 2>&1`?
  validations:
    required: false
- type: dropdown
  id: contribute
  attributes:
    label: Do you want to contribute a patch to fix the issue?
    multiple: false
    options:
      - Yes, I'm glad to submit a patch to fix it
      - No.
